RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at ../torch/csrc/jit/passes/alias_analysis.cpp:311,  please report a bug to PyTorch. We don't have an op for aten::ones but it isn't a special case. (analyzeImpl at ../torch/csrc/jit/passes/alias_analysis.cpp:311)