 torch.normal / torch.distributions
# Bug description: Tracer throws runtime exception for torch.normal in PyTorch v0.4.1
